import argparse
import io
import json
import math
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

from apps.admin.common import ADMIN_ENV_PATH, ROOT_DIR
from apps.admin.utils import portal_db
from apps.admin.utils.r2_storage import is_r2_configured, read_text_key


DEFAULT_BATCH_YEARS = ['2021', '2022', '2023', '2024', '2025']
DEFAULT_OUTPUT_DIR = 'apps/admin/d1_import'
DEFAULT_STATEMENT_BYTES = 80_000

SEMESTER_INSERT_COLUMNS = [
    'student_id', 'batch_year', 'semester_number', 'subject_code',
    'subject_name', 'grade', 'credits', 'row_order',
    'is_honors_minor', 'sync_token',
]

TOPPERS_INSERT_COLUMNS = [
    'batch_year', 'category', 'roll_number', 'cgpa', 'rank_order', 'sync_token',
]

NOTIFICATION_INSERT_COLUMNS = [
    'text', 'date_text', 'is_new', 'sort_order',
]


def read_optional_r2_key(key):
    try:
        _, content = read_text_key(key)
        return content
    except Exception as exc:
        message = str(exc)
        if 'NoSuchKey' in message or '404' in message or 'not found' in message.lower():
            return None
        raise


def parse_years(raw_years):
    if raw_years:
        return [year.strip() for year in raw_years.split(',') if year.strip()]

    env_years = os.getenv('D1_MIGRATION_BATCH_YEARS')
    if env_years:
        return [year.strip() for year in env_years.split(',') if year.strip()]

    return DEFAULT_BATCH_YEARS


def dataframe_from_csv(csv_text):
    return pd.read_csv(io.StringIO(csv_text), encoding='utf-8-sig')


def write_schema_file(output_dir):
    schema_path = ROOT_DIR / 'apps' / 'admin' / 'migrations' / 'd1_schema.sql'
    output_path = output_dir / '00_schema.sql'
    output_path.write_text(schema_path.read_text(encoding='utf-8'), encoding='utf-8')
    return output_path


def write_import_file(output_path, table, columns, rows, insert_prefix='INSERT OR IGNORE', max_statement_bytes=DEFAULT_STATEMENT_BYTES):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf-8', newline='\n') as output_file:
        output_file.write('-- Generated by generate_d1_wrangler_import_sql.py\n')
        output_file.write('-- Wrangler imports still count toward D1 rows written.\n\n')
        if not rows:
            output_file.write(f'-- No rows for {table}.\n')
            return 0

        written = 0
        statement_rows = []
        statement_size = 0
        header = f"{insert_prefix} INTO {table} ({', '.join(columns)}) VALUES\n"

        for row in rows:
            tuple_sql = '(' + ', '.join(sql_literal(row.get(column)) for column in columns) + ')'
            tuple_size = len(tuple_sql.encode('utf-8')) + 4
            if statement_rows and statement_size + tuple_size + len(header.encode('utf-8')) > max_statement_bytes:
                output_file.write(header)
                output_file.write(',\n'.join(statement_rows))
                output_file.write(';\n\n')
                written += len(statement_rows)
                statement_rows = []
                statement_size = 0

            statement_rows.append(tuple_sql)
            statement_size += tuple_size

        if statement_rows:
            output_file.write(header)
            output_file.write(',\n'.join(statement_rows))
            output_file.write(';\n')
            written += len(statement_rows)

    return written


def write_cgpa_file(output_dir, year, csv_text, max_statement_bytes):
    dataframe = dataframe_from_csv(csv_text)
    sync_token = f'wrangler-cgpa-{year}'
    cgpa_rows = portal_db._cgpa_rows_from_dataframe(year, dataframe, sync_token)
    summary_rows = [
        portal_db._academic_summary_row_from_cgpa_row(row, f'wrangler-academic-summary-{year}')
        for row in cgpa_rows
    ]

    output_path = output_dir / f'{year}_01_cgpa_and_summary.sql'
    with output_path.open('w', encoding='utf-8', newline='\n') as output_file:
        output_file.write('-- Generated by generate_d1_wrangler_import_sql.py\n')
        output_file.write('-- Wrangler imports still count toward D1 rows written.\n\n')

    cgpa_count = append_insert_statements(
        output_path,
        'student_cgpa',
        portal_db.CGPA_INSERT_COLUMNS,
        cgpa_rows,
        max_statement_bytes=max_statement_bytes,
    )
    summary_count = append_insert_statements(
        output_path,
        'student_academic_summary',
        portal_db.ACADEMIC_SUMMARY_INSERT_COLUMNS,
        summary_rows,
        max_statement_bytes=max_statement_bytes,
    )
    return output_path, cgpa_count + summary_count


def append_insert_statements(output_path, table, columns, rows, max_statement_bytes=DEFAULT_STATEMENT_BYTES):
    with output_path.open('a', encoding='utf-8', newline='\n') as output_file:
        if not rows:
            output_file.write(f'-- No rows for {table}.\n\n')
            return 0

        written = 0
        statement_rows = []
        statement_size = 0
        header = f"INSERT OR IGNORE INTO {table} ({', '.join(columns)}) VALUES\n"

        for row in rows:
            tuple_sql = '(' + ', '.join(sql_literal(row.get(column)) for column in columns) + ')'
            tuple_size = len(tuple_sql.encode('utf-8')) + 4
            if statement_rows and statement_size + tuple_size + len(header.encode('utf-8')) > max_statement_bytes:
                output_file.write(header)
                output_file.write(',\n'.join(statement_rows))
                output_file.write(';\n\n')
                written += len(statement_rows)
                statement_rows = []
                statement_size = 0

            statement_rows.append(tuple_sql)
            statement_size += tuple_size

        if statement_rows:
            output_file.write(header)
            output_file.write(',\n'.join(statement_rows))
            output_file.write(';\n\n')
            written += len(statement_rows)

    return written


def write_semester_file(output_dir, year, semester, csv_text, max_statement_bytes):
    dataframe = dataframe_from_csv(csv_text)
    rows = portal_db._semester_rows_from_dataframe(
        year,
        semester,
        dataframe,
        is_honors_minor=(semester == 9),
        sync_token=f'wrangler-semester-{year}-{semester}',
    )
    output_path = output_dir / f'{year}_{semester + 1:02d}_semester{semester}.sql'
    row_count = write_import_file(
        output_path,
        'semester_results',
        SEMESTER_INSERT_COLUMNS,
        rows,
        max_statement_bytes=max_statement_bytes,
    )
    return output_path, row_count


def write_toppers_file(output_dir, year, csv_text, max_statement_bytes):
    dataframe = dataframe_from_csv(csv_text)
    rows = portal_db._toppers_rows_from_dataframe(
        year,
        dataframe,
        sync_token=f'wrangler-toppers-{year}',
    )
    output_path = output_dir / f'{year}_11_toppers.sql'
    row_count = write_import_file(
        output_path,
        'toppers',
        TOPPERS_INSERT_COLUMNS,
        rows,
        max_statement_bytes=max_statement_bytes,
    )
    return output_path, row_count


def write_notifications_file(output_dir, json_text, max_statement_bytes):
    notifications = json.loads(json_text)
    rows = []
    for index, item in enumerate(notifications or []):
        if not isinstance(item, dict):
            continue
        text = str(item.get('text') or '').strip()
        if not text:
            continue
        rows.append({
            'text': text,
            'date_text': str(item.get('date') or '').strip(),
            'is_new': 1 if item.get('is_new') else 0,
            'sort_order': index,
        })

    output_path = output_dir / 'zz_notifications.sql'
    with output_path.open('w', encoding='utf-8', newline='\n') as output_file:
        output_file.write('-- Generated by generate_d1_wrangler_import_sql.py\n')
        output_file.write('-- This small file replaces notifications to avoid duplicates.\n\n')
        output_file.write('DELETE FROM notifications;\n\n')

    row_count = append_insert_statements(
        output_path,
        'notifications',
        NOTIFICATION_INSERT_COLUMNS,
        rows,
        max_statement_bytes=max_statement_bytes,
    )
    return output_path, row_count


def write_combined_file(output_dir, generated_files, output_name='full_import.sql'):
    output_path = output_dir / output_name
    with output_path.open('w', encoding='utf-8', newline='\n') as output_file:
        output_file.write('-- Combined D1 import SQL generated by generate_d1_wrangler_import_sql.py\n')
        output_file.write('-- Wrangler imports still count toward D1 rows written.\n\n')
        for path in generated_files:
            output_file.write(f'-- BEGIN {path.name}\n')
            output_file.write(path.read_text(encoding='utf-8'))
            output_file.write(f'\n-- END {path.name}\n\n')
    return output_path


def write_command_file(output_dir, generated_files, database_name):
    output_path = output_dir / 'run_wrangler_import.ps1'
    lines = [
        '# Generated by generate_d1_wrangler_import_sql.py',
        '# Replace the database name if needed. Wrangler imports still count toward D1 rows written.',
        f'$databaseName = "{database_name}"',
        '',
    ]
    for path in generated_files:
        relative_path = str(path).replace('/', '\\')
        lines.append(f'npx wrangler d1 execute $databaseName --remote --file="{relative_path}"')
    output_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return output_path


def sql_literal(value):
    if value is None:
        return 'NULL'
    if isinstance(value, bool):
        return '1' if value else '0'
    if isinstance(value, float):
        if math.isnan(value):
            return 'NULL'
        return repr(value)
    if isinstance(value, int):
        return str(value)

    text = str(value)
    if text == '':
        return "''"
    return "'" + text.replace("'", "''") + "'"


def main():
    parser = argparse.ArgumentParser(description='Generate Wrangler-ready SQL files from existing R2 data/ objects.')
    parser.add_argument('--years', help='Comma-separated batch years. Defaults to 2021,2022,2023,2024,2025.')
    parser.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR, help=f'Output folder. Defaults to {DEFAULT_OUTPUT_DIR}.')
    parser.add_argument('--no-schema', action='store_true', help='Do not generate 00_schema.sql.')
    parser.add_argument('--no-notifications', action='store_true', help='Do not generate zz_notifications.sql.')
    parser.add_argument('--single-file', action='store_true', help='Also generate one combined full_import.sql file and command.')
    parser.add_argument('--database-name', default=os.getenv('D1_DATABASE_NAME', '<your-d1-database-name>'), help='D1 database name for generated Wrangler commands.')
    parser.add_argument('--statement-bytes', type=int, default=DEFAULT_STATEMENT_BYTES, help='Max bytes per INSERT statement. Default: 80000.')
    args = parser.parse_args()

    load_dotenv(ADMIN_ENV_PATH)

    if not is_r2_configured():
        raise SystemExit('Missing R2 configuration. This generator reads existing data/ objects from R2.')

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated_files = []
    totals = {}

    if not args.no_schema:
        schema_file = write_schema_file(output_dir)
        generated_files.append(schema_file)
        print(f'{schema_file} generated')

    for year in parse_years(args.years):
        cgpa_key = f'data/cgpa_data_{year}.csv'
        cgpa_content = read_optional_r2_key(cgpa_key)
        if cgpa_content:
            path, row_count = write_cgpa_file(output_dir, year, cgpa_content, args.statement_bytes)
            generated_files.append(path)
            totals[str(path)] = row_count
            print(f'{cgpa_key} -> {path} ({row_count} row values)')
        else:
            print(f'{cgpa_key} skipped: not found')

        for semester in range(1, 10):
            semester_key = f'data/semesters/{year}/semester{semester}.csv'
            semester_content = read_optional_r2_key(semester_key)
            if not semester_content:
                print(f'{semester_key} skipped: not found')
                continue
            path, row_count = write_semester_file(output_dir, year, semester, semester_content, args.statement_bytes)
            generated_files.append(path)
            totals[str(path)] = row_count
            print(f'{semester_key} -> {path} ({row_count} row values)')

        toppers_key = f'data/toppers_{year}.csv'
        toppers_content = read_optional_r2_key(toppers_key)
        if toppers_content:
            path, row_count = write_toppers_file(output_dir, year, toppers_content, args.statement_bytes)
            generated_files.append(path)
            totals[str(path)] = row_count
            print(f'{toppers_key} -> {path} ({row_count} row values)')
        else:
            print(f'{toppers_key} skipped: not found')

    if not args.no_notifications:
        notifications_key = 'data/notifications.json'
        notifications_content = read_optional_r2_key(notifications_key)
        if notifications_content:
            path, row_count = write_notifications_file(output_dir, notifications_content, args.statement_bytes)
            generated_files.append(path)
            totals[str(path)] = row_count
            print(f'{notifications_key} -> {path} ({row_count} row values)')
        else:
            print(f'{notifications_key} skipped: not found')

    command_files = generated_files
    if args.single_file:
        combined_file = write_combined_file(output_dir, generated_files)
        command_files = [combined_file]
        print(f'Combined import file: {combined_file}')

    command_file = write_command_file(output_dir, command_files, args.database_name)
    print(f'\nWrangler command file: {command_file}')
    print('Run only the SQL files you need; imports still count toward D1 row-write usage.')


if __name__ == '__main__':
    main()
